--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["Authentication.Login.Action.LogInCapitalized"] = [[Masuk]],
	["Authentication.Login.Action.WeChatLogin"] = [[Masuk WeChat]],
	["Authentication.SignUp.Label.SignUp"] = [[Daftar]],
	["Authentication.SignUp.Description.ByTappingSign"] = [[Dengan mengetuk 'Daftar' di atas, kamu menyetujui ]],
	["Authentication.SignUp.Label.WhensYourBirthday"] = [[Kapan ulang tahunmu?]],
	["CommonUI.Controls.Label.April"] = [[April]],
	["CommonUI.Controls.Label.August"] = [[Agustus]],
	["CommonUI.Controls.Label.December"] = [[Desember]],
	["CommonUI.Controls.Label.February"] = [[Februari]],
	["CommonUI.Controls.Label.January"] = [[Januari]],
	["CommonUI.Controls.Label.July"] = [[Juli]],
	["CommonUI.Controls.Label.June"] = [[Juni]],
	["CommonUI.Controls.Label.March"] = [[Maret]],
	["CommonUI.Controls.Label.May"] = [[Mei]],
	["CommonUI.Controls.Label.November"] = [[November]],
	["CommonUI.Controls.Label.October"] = [[Oktober]],
	["CommonUI.Controls.Label.September"] = [[September]],
	["CommonUI.Features.Label.Avatar"] = [[Avatar]],
	["CommonUI.Features.Label.Blog"] = [[Blog]],
	["CommonUI.Features.Label.BuildersClub"] = [[Keanggotaan]],
	["CommonUI.Features.Label.Catalog"] = [[Katalog]],
	["CommonUI.Features.Label.Chat"] = [[Obrolan]],
	["CommonUI.Features.Label.Events"] = [[Event]],
	["CommonUI.Features.Label.Friends"] = [[Teman]],
	["CommonUI.Features.Label.Game"] = [[Game]],
	["CommonUI.Features.Label.Groups"] = [[Grup]],
	["CommonUI.Features.Label.Help"] = [[Bantuan]],
	["CommonUI.Features.Label.Home"] = [[Beranda]],
	["CommonUI.Features.Label.Inventory"] = [[Inventaris]],
	["CommonUI.Features.Label.Messages"] = [[Pesan]],
	["CommonUI.Features.Label.More"] = [[Lainnya]],
	["CommonUI.Features.Label.Profile"] = [[Profil]],
	["CommonUI.Features.Label.Settings"] = [[Pengaturan]],
	["CommonUI.Features.Label.TermsOfService"] = [[Ketentuan Layanan]],
	["CommonUI.Features.Label.PrivacyPolicy"] = [[Kebijakan Privasi]],
	["CommonUI.Features.Label.About"] = [[Tentang]],
	["CommonUI.Features.Label.AboutUs"] = [[Tentang Kami]],
	["CommonUI.Features.Label.Careers"] = [[Karier]],
	["CommonUI.Features.Label.Parents"] = [[Orang Tua]],
	["CommonUI.Features.Label.Terms"] = [[Ketentuan]],
	["CommonUI.Features.Label.Privacy"] = [[Privasi]],
	["CommonUI.Features.Label.Version"] = [[Versi]],
	["CommonUI.Features.Label.MoreEvents"] = [[Event lainnya segera hadir!]],
	["CommonUI.Features.Heading.GameDetails"] = [[Detail Game]],
	["CommonUI.Features.Label.Players"] = [[Pemain]],
	["CommonUI.Features.Label.Create"] = [[Buat]],
	["CommonUI.Features.Label.Badges"] = [[Lencana]],
	["CommonUI.Features.Label.MyFeed"] = [[Feed Saya]],
	["CommonUI.Features.Label.CreateGames"] = [[Buat Game]],
	["CommonUI.Features.Label.VersionWithNumber"] = [[Versi:{versionNumber}]],
	["CommonUI.Features.Label.Challenge"] = [[Tantangan]],
	["CommonUI.Features.Heading.ItemDetails"] = [[Detail Item]],
	["CommonUI.Features.Label.Startup"] = [[Memulai]],
	["CommonUI.Features.Label.Discussions"] = [[Diskusi]],
	["CommonUI.Messages.Description.And"] = [[dan]],
	["CommonUI.Messages.Action.OK"] = [[OKE]],
	["CommonUI.Messages.Label.Alert"] = [[Peringatan]],
}