--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["Authentication.Login.Action.LogInCapitalized"] = [[Accedi]],
	["Authentication.Login.Action.WeChatLogin"] = [[Accesso a WeChat]],
	["Authentication.SignUp.Label.SignUp"] = [[Registrati]],
	["Authentication.SignUp.Description.ByTappingSign"] = [[Toccando "Registrati" in alto, accetti ]],
	["Authentication.SignUp.Label.WhensYourBirthday"] = [[Qual è la tua data di nascita?]],
	["CommonUI.Controls.Label.April"] = [[Aprile]],
	["CommonUI.Controls.Label.August"] = [[Agosto]],
	["CommonUI.Controls.Label.December"] = [[Dicembre]],
	["CommonUI.Controls.Label.February"] = [[Febbraio]],
	["CommonUI.Controls.Label.January"] = [[Gennaio]],
	["CommonUI.Controls.Label.July"] = [[Luglio]],
	["CommonUI.Controls.Label.June"] = [[Giugno]],
	["CommonUI.Controls.Label.March"] = [[Marzo]],
	["CommonUI.Controls.Label.May"] = [[Maggio]],
	["CommonUI.Controls.Label.November"] = [[Novembre]],
	["CommonUI.Controls.Label.October"] = [[Ottobre]],
	["CommonUI.Controls.Label.September"] = [[Settembre]],
	["CommonUI.Features.Label.Avatar"] = [[Avatar]],
	["CommonUI.Features.Label.Blog"] = [[Blog]],
	["CommonUI.Features.Label.BuildersClub"] = [[Abbonamento]],
	["CommonUI.Features.Label.Catalog"] = [[Catalogo]],
	["CommonUI.Features.Label.Chat"] = [[Chat]],
	["CommonUI.Features.Label.Events"] = [[Eventi]],
	["CommonUI.Features.Label.Friends"] = [[Amici]],
	["CommonUI.Features.Label.Game"] = [[Giochi]],
	["CommonUI.Features.Label.Groups"] = [[Gruppi]],
	["CommonUI.Features.Label.Help"] = [[Guida]],
	["CommonUI.Features.Label.Home"] = [[Home]],
	["CommonUI.Features.Label.Inventory"] = [[Inventario]],
	["CommonUI.Features.Label.Messages"] = [[Messaggi]],
	["CommonUI.Features.Label.More"] = [[Altro]],
	["CommonUI.Features.Label.Profile"] = [[Profilo]],
	["CommonUI.Features.Label.Settings"] = [[Impostazioni]],
	["CommonUI.Features.Label.TermsOfService"] = [[Termini di servizio]],
	["CommonUI.Features.Label.PrivacyPolicy"] = [[Informativa sulla privacy]],
	["CommonUI.Features.Label.About"] = [[Info]],
	["CommonUI.Features.Label.AboutUs"] = [[Su di noi]],
	["CommonUI.Features.Label.Careers"] = [[Lavora con noi]],
	["CommonUI.Features.Label.Parents"] = [[Genitori]],
	["CommonUI.Features.Label.Terms"] = [[Temini]],
	["CommonUI.Features.Label.Privacy"] = [[Privacy]],
	["CommonUI.Features.Label.Version"] = [[Versione]],
	["CommonUI.Features.Label.MoreEvents"] = [[Prossimamente altri eventi!]],
	["CommonUI.Features.Heading.GameDetails"] = [[Dettagli di gioco]],
	["CommonUI.Features.Label.Players"] = [[Giocatori]],
	["CommonUI.Features.Label.Create"] = [[Crea]],
	["CommonUI.Features.Label.Badges"] = [[Contrassegni]],
	["CommonUI.Features.Label.MyFeed"] = [[I miei Feed]],
	["CommonUI.Features.Label.CreateGames"] = [[Crea partite]],
	["CommonUI.Features.Label.VersionWithNumber"] = [[Versione: {versionNumber}]],
	["CommonUI.Features.Label.Challenge"] = [[Sfide]],
	["CommonUI.Features.Heading.ItemDetails"] = [[Dettagli oggetto]],
	["CommonUI.Features.Label.Startup"] = [[Avvio]],
	["CommonUI.Features.Label.Discussions"] = [[Discussioni]],
	["CommonUI.Messages.Description.And"] = [[e]],
	["CommonUI.Messages.Action.OK"] = [[OK]],
	["CommonUI.Messages.Label.Alert"] = [[Avviso]],
	["Feature.PremiumMigration.PopUp.Title"] = [[Aggiornamenti in Roblox Premium]],
	["Feature.PremiumMigration.PopUp.Body"] = [[La versione Premium ora ti regala una somma mensile di Robux tutta in una volta, invece che assegnartela quotidianamente! Oggi riceverai la tua somma mensile meno quanto hai già ricevuto durante questo mese. Riceverai: R${robuxAmount}.

Controlla la tua posta in arrivo Roblox per maggiori informazioni.]],
}