--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["Authentication.Login.Action.LogInCapitalized"] = [[Вход]],
	["Authentication.Login.Action.WeChatLogin"] = [[Вход в WeChat]],
	["Authentication.SignUp.Label.SignUp"] = [[Регистрация]],
	["Authentication.SignUp.Description.ByTappingSign"] = [[Нажав на кнопку «Регистрация», вы принимаете наши ]],
	["Authentication.SignUp.Label.WhensYourBirthday"] = [[Когда у вас день рождения?]],
	["CommonUI.Controls.Label.April"] = [[Апрель]],
	["CommonUI.Controls.Label.August"] = [[Август]],
	["CommonUI.Controls.Label.December"] = [[Декабрь]],
	["CommonUI.Controls.Label.February"] = [[Февраль]],
	["CommonUI.Controls.Label.January"] = [[Январь]],
	["CommonUI.Controls.Label.July"] = [[Июль]],
	["CommonUI.Controls.Label.June"] = [[Июнь]],
	["CommonUI.Controls.Label.March"] = [[Март]],
	["CommonUI.Controls.Label.May"] = [[Май]],
	["CommonUI.Controls.Label.November"] = [[Ноябрь]],
	["CommonUI.Controls.Label.October"] = [[Октябрь]],
	["CommonUI.Controls.Label.September"] = [[Сентябрь]],
	["CommonUI.Features.Label.Avatar"] = [[Аватар]],
	["CommonUI.Features.Label.Blog"] = [[Блог]],
	["CommonUI.Features.Label.BuildersClub"] = [[Участие]],
	["CommonUI.Features.Label.Catalog"] = [[Каталог]],
	["CommonUI.Features.Label.Chat"] = [[Чат]],
	["CommonUI.Features.Label.Events"] = [[Акции]],
	["CommonUI.Features.Label.Friends"] = [[Друзья]],
	["CommonUI.Features.Label.Game"] = [[Игры]],
	["CommonUI.Features.Label.Groups"] = [[Группы]],
	["CommonUI.Features.Label.Help"] = [[Справка]],
	["CommonUI.Features.Label.Home"] = [[Главная]],
	["CommonUI.Features.Label.Inventory"] = [[Инвентарь]],
	["CommonUI.Features.Label.Messages"] = [[Сообщения]],
	["CommonUI.Features.Label.More"] = [[Больше]],
	["CommonUI.Features.Label.Profile"] = [[Профиль]],
	["CommonUI.Features.Label.Settings"] = [[Настройки]],
	["CommonUI.Features.Label.TermsOfService"] = [[Условия предоставления услуг]],
	["CommonUI.Features.Label.PrivacyPolicy"] = [[Политика конфиденциальности]],
	["CommonUI.Features.Label.About"] = [[Сведения]],
	["CommonUI.Features.Label.AboutUs"] = [[О нас]],
	["CommonUI.Features.Label.Careers"] = [[Работа]],
	["CommonUI.Features.Label.Parents"] = [[Родители]],
	["CommonUI.Features.Label.Terms"] = [[Условия]],
	["CommonUI.Features.Label.Privacy"] = [[Конфиденциальность]],
	["CommonUI.Features.Label.Version"] = [[Версия]],
	["CommonUI.Features.Label.MoreEvents"] = [[Новые события – уже скоро!]],
	["CommonUI.Features.Heading.GameDetails"] = [[Сведения об игре]],
	["CommonUI.Features.Label.Players"] = [[Игроки]],
	["CommonUI.Features.Label.Create"] = [[Создать]],
	["CommonUI.Features.Label.Badges"] = [[Значки]],
	["CommonUI.Features.Label.MyFeed"] = [[Лента]],
	["CommonUI.Features.Label.CreateGames"] = [[Создать игры]],
	["CommonUI.Features.Label.VersionWithNumber"] = [[Версия:{versionNumber}]],
	["CommonUI.Features.Label.Challenge"] = [[Состязания]],
	["CommonUI.Features.Heading.ItemDetails"] = [[Сведения о предмете]],
	["CommonUI.Features.Label.Startup"] = [[Стартап]],
	["CommonUI.Features.Label.Discussions"] = [[Обсуждения]],
	["CommonUI.Messages.Description.And"] = [[и]],
	["CommonUI.Messages.Action.OK"] = [[OK]],
	["CommonUI.Messages.Label.Alert"] = [[Тревога]],
	["Feature.PremiumMigration.PopUp.Title"] = [[Улучшение до Roblox Премиум]],
	["Feature.PremiumMigration.PopUp.Body"] = [[Сейчас Премиум дает вам сразу месячный допуск к Robux вместо каждодневного! Сегодня мы предоставляем вам месячный допуск за вычетом того, что вы уже получили в этом месяце. Вы получите: R${robuxAmount}.

Зайдите в свою учетную запись Roblox, чтобы получить подробные сведения.]],
}