--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["Authentication.Login.Action.LogInCapitalized"] = [[เข้าสู่ระบบ]],
	["Authentication.Login.Action.WeChatLogin"] = [[เข้าสู่ระบบ WeChat]],
	["Authentication.SignUp.Label.SignUp"] = [[สมัครบัญชีผู้ใช้]],
	["Authentication.SignUp.Description.ByTappingSign"] = [[การแตะที่ "สมัครบัญชีผู้ใช้" ด้านบน จะถือว่าคุณยอมรับ ]],
	["Authentication.SignUp.Label.WhensYourBirthday"] = [[วันเกิดของคุณวันที่เท่าไร?]],
	["CommonUI.Controls.Label.April"] = [[เมษายน]],
	["CommonUI.Controls.Label.August"] = [[สิงหาคม]],
	["CommonUI.Controls.Label.December"] = [[ธันวาคม]],
	["CommonUI.Controls.Label.February"] = [[กุมภาพันธ์]],
	["CommonUI.Controls.Label.January"] = [[มกราคม]],
	["CommonUI.Controls.Label.July"] = [[กรกฎาคม]],
	["CommonUI.Controls.Label.June"] = [[มิถุนายน]],
	["CommonUI.Controls.Label.March"] = [[มีนาคม]],
	["CommonUI.Controls.Label.May"] = [[พฤษภาคม]],
	["CommonUI.Controls.Label.November"] = [[พฤศจิกายน]],
	["CommonUI.Controls.Label.October"] = [[ตุลาคม]],
	["CommonUI.Controls.Label.September"] = [[กันยายน]],
	["CommonUI.Features.Label.Avatar"] = [[อวตาร]],
	["CommonUI.Features.Label.Blog"] = [[บล็อก]],
	["CommonUI.Features.Label.BuildersClub"] = [[สถานะสมาชิก]],
	["CommonUI.Features.Label.Catalog"] = [[แค็ตตาล็อก]],
	["CommonUI.Features.Label.Chat"] = [[แชต]],
	["CommonUI.Features.Label.Events"] = [[อีเวนต์]],
	["CommonUI.Features.Label.Friends"] = [[เพื่อน]],
	["CommonUI.Features.Label.Game"] = [[เกม]],
	["CommonUI.Features.Label.Groups"] = [[กลุ่ม]],
	["CommonUI.Features.Label.Help"] = [[ช่วยเหลือ]],
	["CommonUI.Features.Label.Home"] = [[หน้าหลัก]],
	["CommonUI.Features.Label.Inventory"] = [[คลังไอเทม]],
	["CommonUI.Features.Label.Messages"] = [[ข้อความ]],
	["CommonUI.Features.Label.More"] = [[เพิ่มเติม]],
	["CommonUI.Features.Label.Profile"] = [[ประวัติ]],
	["CommonUI.Features.Label.Settings"] = [[การตั้งค่า]],
	["CommonUI.Features.Label.TermsOfService"] = [[เงื่อนไขการให้บริการ]],
	["CommonUI.Features.Label.PrivacyPolicy"] = [[นโยบายความเป็นส่วนตัว]],
	["CommonUI.Features.Label.About"] = [[เกี่ยวกับ]],
	["CommonUI.Features.Label.AboutUs"] = [[เกี่ยวกับเรา]],
	["CommonUI.Features.Label.Careers"] = [[อาชีพการงาน]],
	["CommonUI.Features.Label.Parents"] = [[ผู้ปกครอง]],
	["CommonUI.Features.Label.Terms"] = [[เงื่อนไข]],
	["CommonUI.Features.Label.Privacy"] = [[ความเป็นส่วนตัว]],
	["CommonUI.Features.Label.Version"] = [[เวอร์ชัน]],
	["CommonUI.Features.Label.MoreEvents"] = [[จะมีอีเวนต์เพิ่มเติมเร็วๆ นี้!]],
	["CommonUI.Features.Heading.GameDetails"] = [[รายละเอียดเกม]],
	["CommonUI.Features.Label.Players"] = [[ผู้เล่น]],
	["CommonUI.Features.Label.Create"] = [[สร้าง]],
	["CommonUI.Features.Label.Badges"] = [[ตรา]],
	["CommonUI.Features.Label.MyFeed"] = [[ฟีดข้อมูลของฉัน]],
	["CommonUI.Features.Label.CreateGames"] = [[สร้างเกม]],
	["CommonUI.Features.Label.VersionWithNumber"] = [[เวอร์ชัน:{versionNumber}]],
	["CommonUI.Features.Label.Challenge"] = [[ความท้าทาย]],
	["CommonUI.Features.Heading.ItemDetails"] = [[ละเอียดของรายการ]],
	["CommonUI.Features.Label.Startup"] = [[เริ่มต้น]],
	["CommonUI.Features.Label.Discussions"] = [[การสนทนา]],
	["CommonUI.Messages.Description.And"] = [[และ]],
	["CommonUI.Messages.Action.OK"] = [[ตกลง]],
	["CommonUI.Messages.Label.Alert"] = [[แจ้งเตือน]],
}