--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["Authentication.Login.Action.LogInCapitalized"] = [[Giriş Yap]],
	["Authentication.Login.Action.WeChatLogin"] = [[WeChat Girişi]],
	["Authentication.SignUp.Label.SignUp"] = [[Kaydol]],
	["Authentication.SignUp.Description.ByTappingSign"] = [[Yukarıdaki 'Kayıt ol'a dokunarak kabul etmiş olursun: ]],
	["Authentication.SignUp.Label.WhensYourBirthday"] = [[Doğum günün ne zaman?]],
	["CommonUI.Controls.Label.April"] = [[Nisan]],
	["CommonUI.Controls.Label.August"] = [[Ağustos]],
	["CommonUI.Controls.Label.December"] = [[Aralık]],
	["CommonUI.Controls.Label.February"] = [[Şubat]],
	["CommonUI.Controls.Label.January"] = [[Ocak]],
	["CommonUI.Controls.Label.July"] = [[Temmuz]],
	["CommonUI.Controls.Label.June"] = [[Haziran]],
	["CommonUI.Controls.Label.March"] = [[Mart]],
	["CommonUI.Controls.Label.May"] = [[Mayıs]],
	["CommonUI.Controls.Label.November"] = [[Kasım]],
	["CommonUI.Controls.Label.October"] = [[Ekim]],
	["CommonUI.Controls.Label.September"] = [[Eylül]],
	["CommonUI.Features.Label.Avatar"] = [[Avatar]],
	["CommonUI.Features.Label.Blog"] = [[Blog]],
	["CommonUI.Features.Label.BuildersClub"] = [[Üyelik]],
	["CommonUI.Features.Label.Catalog"] = [[Katalog]],
	["CommonUI.Features.Label.Chat"] = [[Sohbet]],
	["CommonUI.Features.Label.Events"] = [[Etkinlikler]],
	["CommonUI.Features.Label.Friends"] = [[Arkadaşlar]],
	["CommonUI.Features.Label.Game"] = [[Oyunlar]],
	["CommonUI.Features.Label.Groups"] = [[Gruplar]],
	["CommonUI.Features.Label.Help"] = [[Yardım]],
	["CommonUI.Features.Label.Home"] = [[Ana Sayfa]],
	["CommonUI.Features.Label.Inventory"] = [[Envanter]],
	["CommonUI.Features.Label.Messages"] = [[Mesajlar]],
	["CommonUI.Features.Label.More"] = [[Daha Fazla]],
	["CommonUI.Features.Label.Profile"] = [[Profil]],
	["CommonUI.Features.Label.Settings"] = [[Ayarlar]],
	["CommonUI.Features.Label.TermsOfService"] = [[Hizmet Koşulları]],
	["CommonUI.Features.Label.PrivacyPolicy"] = [[Gizlilik Politikası]],
	["CommonUI.Features.Label.About"] = [[Hakkında]],
	["CommonUI.Features.Label.AboutUs"] = [[Hakkımızda]],
	["CommonUI.Features.Label.Careers"] = [[Kariyer]],
	["CommonUI.Features.Label.Parents"] = [[Ebeveyn]],
	["CommonUI.Features.Label.Terms"] = [[Koşullar]],
	["CommonUI.Features.Label.Privacy"] = [[Gizlilik]],
	["CommonUI.Features.Label.Version"] = [[Sürüm]],
	["CommonUI.Features.Label.MoreEvents"] = [[Daha fazla etkinlik yakında geliyor!]],
	["CommonUI.Features.Heading.GameDetails"] = [[Oyun Ayrıntıları]],
	["CommonUI.Features.Label.Players"] = [[Oyuncular]],
	["CommonUI.Features.Label.Create"] = [[Oluştur]],
	["CommonUI.Features.Label.Badges"] = [[Rozetler]],
	["CommonUI.Features.Label.MyFeed"] = [[Akış Listem]],
	["CommonUI.Features.Label.CreateGames"] = [[Oyun Oluştur]],
	["CommonUI.Features.Label.VersionWithNumber"] = [[Sürüm:{versionNumber}]],
	["CommonUI.Features.Label.Challenge"] = [[Mücadeleler]],
	["CommonUI.Features.Heading.ItemDetails"] = [[Öğe Ayrıntıları]],
	["CommonUI.Features.Label.Startup"] = [[Başlangıç]],
	["CommonUI.Features.Label.Discussions"] = [[Tartışmalar]],
	["CommonUI.Messages.Description.And"] = [[ve]],
	["CommonUI.Messages.Action.OK"] = [[Tamam]],
	["CommonUI.Messages.Label.Alert"] = [[Uyarı]],
}