--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: ClientIntegration/Tools/LuaStringsGenerator/GenerateAllLocales.py

		Changes to this file should always follow:
		Building an Internationalized Feature - Engineer's Guide:
		https://confluence.roblox.com/display/IN/Building+an+Internationalized+Feature+-+Engineer%27s+Guide
		Sync up with newly-updated translations:
		https://confluence.roblox.com/display/MOBAPP/Sync+up+with+newly-updated+translations
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]

return{
	["Authentication.Login.Action.LogInCapitalized"] = [[Đăng nhập]],
	["Authentication.Login.Action.WeChatLogin"] = [[Đăng nhập bằng WeChat]],
	["Authentication.SignUp.Label.SignUp"] = [[Đăng ký]],
	["Authentication.SignUp.Description.ByTappingSign"] = [[Nhấn vào mục 'Đăng ký' bên trên đồng nghĩa bạn đồng ý với ]],
	["Authentication.SignUp.Label.WhensYourBirthday"] = [[Ngày sinh của bạn?]],
	["CommonUI.Controls.Label.April"] = [[Tháng 4]],
	["CommonUI.Controls.Label.August"] = [[Tháng 8]],
	["CommonUI.Controls.Label.December"] = [[Tháng 12]],
	["CommonUI.Controls.Label.February"] = [[Tháng 2]],
	["CommonUI.Controls.Label.January"] = [[Tháng 1]],
	["CommonUI.Controls.Label.July"] = [[Tháng 7]],
	["CommonUI.Controls.Label.June"] = [[Tháng 6]],
	["CommonUI.Controls.Label.March"] = [[Tháng 3]],
	["CommonUI.Controls.Label.May"] = [[Tháng 5]],
	["CommonUI.Controls.Label.November"] = [[Tháng 11]],
	["CommonUI.Controls.Label.October"] = [[Tháng 10]],
	["CommonUI.Controls.Label.September"] = [[Tháng 9]],
	["CommonUI.Features.Label.Avatar"] = [[Hình đại diện]],
	["CommonUI.Features.Label.Blog"] = [[Blog]],
	["CommonUI.Features.Label.BuildersClub"] = [[Quyền thành viên]],
	["CommonUI.Features.Label.Catalog"] = [[Danh mục]],
	["CommonUI.Features.Label.Chat"] = [[Trò chuyện]],
	["CommonUI.Features.Label.Events"] = [[Sự kiện]],
	["CommonUI.Features.Label.Friends"] = [[Bạn bè]],
	["CommonUI.Features.Label.Game"] = [[Trò chơi]],
	["CommonUI.Features.Label.Groups"] = [[Nhóm]],
	["CommonUI.Features.Label.Help"] = [[Trợ giúp]],
	["CommonUI.Features.Label.Home"] = [[Trang chủ]],
	["CommonUI.Features.Label.Inventory"] = [[Kho]],
	["CommonUI.Features.Label.Messages"] = [[Tin nhắn]],
	["CommonUI.Features.Label.More"] = [[Thêm]],
	["CommonUI.Features.Label.Profile"] = [[Hồ sơ]],
	["CommonUI.Features.Label.Settings"] = [[Cài đặt]],
	["CommonUI.Features.Label.TermsOfService"] = [[Điều khoản dịch vụ]],
	["CommonUI.Features.Label.PrivacyPolicy"] = [[Chính sách riêng tư]],
	["CommonUI.Features.Label.About"] = [[Về sản phẩm]],
	["CommonUI.Features.Label.AboutUs"] = [[Về chúng tôi]],
	["CommonUI.Features.Label.Careers"] = [[Tuyển dụng]],
	["CommonUI.Features.Label.Parents"] = [[Cha mẹ]],
	["CommonUI.Features.Label.Terms"] = [[Điều khoản]],
	["CommonUI.Features.Label.Privacy"] = [[Riêng tư]],
	["CommonUI.Features.Label.Version"] = [[Phiên bản]],
	["CommonUI.Features.Label.MoreEvents"] = [[Sớm ra mắt thêm sự kiện!]],
	["CommonUI.Features.Heading.GameDetails"] = [[Chi tiết về game]],
	["CommonUI.Features.Label.Players"] = [[Người chơi]],
	["CommonUI.Features.Label.Create"] = [[Tạo]],
	["CommonUI.Features.Label.Badges"] = [[Huy hiệu]],
	["CommonUI.Features.Label.MyFeed"] = [[Nguồn tin của tôi]],
	["CommonUI.Features.Label.CreateGames"] = [[Tạo trò chơi]],
	["CommonUI.Features.Label.VersionWithNumber"] = [[Phiên bản:{versionNumber}]],
	["CommonUI.Features.Label.Challenge"] = [[Thử thách]],
	["CommonUI.Features.Heading.ItemDetails"] = [[Chi tiết về mục]],
	["CommonUI.Features.Label.Startup"] = [[Khởi động]],
	["CommonUI.Features.Label.Discussions"] = [[Các cuộc thảo luận]],
	["CommonUI.Messages.Description.And"] = [[và]],
	["CommonUI.Messages.Action.OK"] = [[OK]],
	["CommonUI.Messages.Label.Alert"] = [[Thông báo]],
}