return {
	ChatConversationHeaderGroupDetails = "ChatConversationHeaderGroupDetails",
	ChatHeaderSearch = "ChatHeaderSearch",
	ChatHeaderCreateChatGroup = "ChatHeaderCreateChatGroup",
	ChatHeaderHomeButton = "ChatHeaderHomeButton",
	ChatHeaderNotifications = "ChatHeaderNotifications",
	ChatPlayTogether = "ChatPlayTogether",
	ChatShareGameToChatFromChat = "ChatShareGameToChatFromChat",
	ChatTapConversationThumbnail = "ChatTapConversationThumbnail",
	GameDetailsMorePage = "GameDetailsMorePage",
	GameDetailsSubtitle = "GameDetailsSubtitle",
	GameInfoList = "GameInfoList",
	GamePlaysAndRatings = "GamePlaysAndRatings",
	Notifications = "Notifications",
	RecommendedGames = "RecommendedGames",
	SearchBar = "SearchBar",
	MorePageType = "MorePageType",
	SocialLinks = "SocialLinks",
	SiteMessageBanner = "SiteMessageBanner",
	UseWidthBasedFormFactorRule = "UseWidthBasedFormFactorRule",
	UseHomePageWithAvatarAndPanel = "UseHomePageWithAvatarAndPanel",
	ShowYouTubeAgeAlert = "ShowYouTubeAgeAlert",
	UseBottomBar = "UseBottomBar",
	AvatarEditorShowBuyRobuxOnTopBar = "AvatarEditorShowBuyRobuxOnTopBar",
	AvatarHeaderIcon = "AvatarHeaderIcon",
	HomeIcon = "HomeIcon",
}
